raw_voxel_size: [8, 8, 8]
gt_voxel_size: [4, 4, 4]
dataset_container: "/groups/cellmap/cellmap/data/jrc_mus-liver/jrc_mus-liver.n5"
fallback_dataset_container: "/nrs/cellmap/pattonw/data/tmp_data/jrc_mus-liver/jrc_mus-liver.n5"
raw_dataset: "volumes/raw"
gt_dataset: "volumes/groundtruth/crop{crop_num}/labels/all"
training_crops:
  - 124
  - 125
  - 132
  - 135
  - 136
  - 137
  - 138
  - 131
  - 133
  - 139
  - 142
  - 143
  - 144
  - 150
  - 151
  - 157
  - 171
  - 172
  - 175
  - 177
  - 183
validation_crops:
  - 145
min_volume_size: 1600
