input_shape_voxels: [28, 28, 28]
num_iterations: 100_000
checkpoint_interval: 1_000
snapshot_interval: 100
batch_size: 2
checkpoint_dir: "/nrs/cellmap/pattonw/context_net/checkpoints"
snapshot_container: "/nrs/cellmap/pattonw/context_net/snapshots.zarr"
loss_file: "/nrs/cellmap/pattonw/context_net/losses.csv"
learning_rate: 0.0004
num_workers: 5
